FROM ubuntu:latest

#set contact email
LABEL contact="burkhajo@ohsu.edu"

RUN apt-get update &&\
 apt-get -y install python3-pip &&\
 pip3 install numpy scipy pandas matplotlib cmapPy &&\
 mkdir /reticula

ADD ./Dockerfile /reticula/
ADD ./executable.py /reticula/

#CMD ["gct2gctx.py","-f GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct","-o GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gctx"]
